/**
 * Demo Data Generator - Realistic feeder list with 4 panels
 * COMPLETE REDESIGN matching actual electrical distribution systems
 * 
 * NEW HIERARCHY (4 Major Panels):
 * TRF-MAIN (Transformer)
 *   ├─ MAIN-DISTRIBUTION (11 items: incomer + 10 distribution feeders/loads)
 *   ├─ UPS-PANEL (10 items: UPS charger, inverter, bypass, etc.)
 *   ├─ HVAC-PANEL (11 items: chillers, AHU, pumps, controls, etc.)
 *   └─ LIGHTING-PANEL (11 items: floor lighting, outdoor, emergency, etc.)
 * 
 * TOTAL: 44 items across 4 panels with realistic hierarchical structure
 */

export const generateDemoData = () => {
  return [
    // ============ SECTION 1: MAIN DISTRIBUTION PANEL (11 items) ============
    {
      'Serial No': 1,
      'Cable Number': 'INC-MAIN-001',
      'Feeder Description': 'MAIN DISTRIBUTION PANEL (MAIN SWITCHGEAR)',
      'From Bus': 'MAIN-DISTRIBUTION',
      'To Bus': 'TRF-MAIN',
      'Voltage (V)': 415,
      'Power Factor': 0.95,
      'Efficiency (%)': 98,
      'Derating Factor': 1.0,
      'Breaker Type': 'ISOLATOR',
      'Load KW': 0,
      'Load KVA': 0,
      'Cable Type': 'XLPE',
      'Installation Method': 'Cable Tray',
      'Ambient Temp (°C)': 35,
      'Ground Temp (°C)': 25,
      'Length (m)': 8.0,
      'Short Circuit Current (kA)': 50,
      'Trip Time (ms)': 100
    },

    // Direct loads under MAIN-DISTRIBUTION
    {
      'Serial No': 2,
      'Cable Number': 'FDR-MAIN-002',
      'Feeder Description': 'Feeder to UPS-PANEL',
      'From Bus': 'UPS-PANEL',
      'To Bus': 'MAIN-DISTRIBUTION',
      'Voltage (V)': 415,
      'Power Factor': 0.90,
      'Efficiency (%)': 95,
      'Derating Factor': 0.87,
      'Breaker Type': 'ACB-250A',
      'Load KW': 85.0,
      'Load KVA': 94.4,
      'Cable Type': 'XLPE',
      'Installation Method': 'Cable Tray',
      'Ambient Temp (°C)': 35,
      'Ground Temp (°C)': 25,
      'Length (m)': 45.0,
      'Short Circuit Current (kA)': 30,
      'Trip Time (ms)': 100
    },

    {
      'Serial No': 3,
      'Cable Number': 'FDR-MAIN-003',
      'Feeder Description': 'Feeder to HVAC-PANEL',
      'From Bus': 'HVAC-PANEL',
      'To Bus': 'MAIN-DISTRIBUTION',
      'Voltage (V)': 415,
      'Power Factor': 0.85,
      'Efficiency (%)': 94,
      'Derating Factor': 0.88,
      'Breaker Type': 'ACB-200A',
      'Load KW': 120.0,
      'Load KVA': 141.2,
      'Cable Type': 'XLPE',
      'Installation Method': 'Cable Tray',
      'Ambient Temp (°C)': 38,
      'Ground Temp (°C)': 28,
      'Length (m)': 55.0,
      'Short Circuit Current (kA)': 28,
      'Trip Time (ms)': 100
    },

    {
      'Serial No': 4,
      'Cable Number': 'FDR-MAIN-004',
      'Feeder Description': 'Feeder to LIGHTING-PANEL',
      'From Bus': 'LIGHTING-PANEL',
      'To Bus': 'MAIN-DISTRIBUTION',
      'Voltage (V)': 415,
      'Power Factor': 0.95,
      'Efficiency (%)': 98,
      'Derating Factor': 0.92,
      'Breaker Type': 'ACB-100A',
      'Load KW': 65.0,
      'Load KVA': 68.4,
      'Cable Type': 'XLPE',
      'Installation Method': 'Cable Tray',
      'Ambient Temp (°C)': 35,
      'Ground Temp (°C)': 25,
      'Length (m)': 35.0,
      'Short Circuit Current (kA)': 25,
      'Trip Time (ms)': 100
    },

    {
      'Serial No': 5,
      'Cable Number': 'LD-MAIN-005',
      'Feeder Description': 'Building Fire Pump Motor - 37kW',
      'From Bus': 'FIRE-PUMP-MOTOR',
      'To Bus': 'MAIN-DISTRIBUTION',
      'Voltage (V)': 415,
      'Power Factor': 0.82,
      'Efficiency (%)': 89,
      'Derating Factor': 0.90,
      'Breaker Type': 'MCCB-100A',
      'Load KW': 37.0,
      'Load KVA': 45.1,
      'Cable Type': 'XLPE',
      'Installation Method': 'Conduit',
      'Ambient Temp (°C)': 35,
      'Ground Temp (°C)': 25,
      'Length (m)': 25.0,
      'Short Circuit Current (kA)': 0,
      'Trip Time (ms)': 0
    },

    {
      'Serial No': 6,
      'Cable Number': 'LD-MAIN-006',
      'Feeder Description': 'Domestic Water Pump Motor - 22kW',
      'From Bus': 'WATER-PUMP-MOTOR',
      'To Bus': 'MAIN-DISTRIBUTION',
      'Voltage (V)': 415,
      'Power Factor': 0.82,
      'Efficiency (%)': 88,
      'Derating Factor': 0.89,
      'Breaker Type': 'MCCB-63A',
      'Load KW': 22.0,
      'Load KVA': 26.8,
      'Cable Type': 'PVC',
      'Installation Method': 'Conduit',
      'Ambient Temp (°C)': 35,
      'Ground Temp (°C)': 25,
      'Length (m)': 30.0,
      'Short Circuit Current (kA)': 0,
      'Trip Time (ms)': 0
    },

    {
      'Serial No': 7,
      'Cable Number': 'LD-MAIN-007',
      'Feeder Description': 'Sewage Treatment Motor - 15kW',
      'From Bus': 'SEWAGE-MOTOR',
      'To Bus': 'MAIN-DISTRIBUTION',
      'Voltage (V)': 415,
      'Power Factor': 0.84,
      'Efficiency (%)': 91,
      'Derating Factor': 0.89,
      'Breaker Type': 'MCCB-50A',
      'Load KW': 15.0,
      'Load KVA': 17.9,
      'Cable Type': 'PVC',
      'Installation Method': 'Conduit',
      'Ambient Temp (°C)': 35,
      'Ground Temp (°C)': 25,
      'Length (m)': 28.0,
      'Short Circuit Current (kA)': 0,
      'Trip Time (ms)': 0
    },

    {
      'Serial No': 8,
      'Cable Number': 'LD-MAIN-008',
      'Feeder Description': 'Elevator Machine Room - 11kW',
      'From Bus': 'ELEVATOR-MOTOR',
      'To Bus': 'MAIN-DISTRIBUTION',
      'Voltage (V)': 415,
      'Power Factor': 0.85,
      'Efficiency (%)': 91,
      'Derating Factor': 0.89,
      'Breaker Type': 'MCCB-32A',
      'Load KW': 11.0,
      'Load KVA': 12.9,
      'Cable Type': 'PVC',
      'Installation Method': 'Conduit',
      'Ambient Temp (°C)': 35,
      'Ground Temp (°C)': 25,
      'Length (m)': 32.0,
      'Short Circuit Current (kA)': 0,
      'Trip Time (ms)': 0
    },

    {
      'Serial No': 9,
      'Cable Number': 'LD-MAIN-009',
      'Feeder Description': 'Emergency Generator Charger - 5kW',
      'From Bus': 'GEN-CHARGER',
      'To Bus': 'MAIN-DISTRIBUTION',
      'Voltage (V)': 415,
      'Power Factor': 0.95,
      'Efficiency (%)': 96,
      'Derating Factor': 0.90,
      'Breaker Type': 'MCB-20A',
      'Load KW': 5.0,
      'Load KVA': 5.3,
      'Cable Type': 'PVC',
      'Installation Method': 'Conduit',
      'Ambient Temp (°C)': 35,
      'Ground Temp (°C)': 25,
      'Length (m)': 22.0,
      'Short Circuit Current (kA)': 0,
      'Trip Time (ms)': 0
    },

    {
      'Serial No': 10,
      'Cable Number': 'LD-MAIN-010',
      'Feeder Description': 'Building Management System - 3kW',
      'From Bus': 'BMS-CONTROL-PANEL',
      'To Bus': 'MAIN-DISTRIBUTION',
      'Voltage (V)': 415,
      'Power Factor': 0.95,
      'Efficiency (%)': 98,
      'Derating Factor': 0.92,
      'Breaker Type': 'MCB-16A',
      'Load KW': 3.0,
      'Load KVA': 3.2,
      'Cable Type': 'PVC',
      'Installation Method': 'Cable Tray',
      'Ambient Temp (°C)': 35,
      'Ground Temp (°C)': 25,
      'Length (m)': 18.0,
      'Short Circuit Current (kA)': 0,
      'Trip Time (ms)': 0
    },

    {
      'Serial No': 11,
      'Cable Number': 'LD-MAIN-011',
      'Feeder Description': 'Parking Lot Exhaust System - 7.5kW',
      'From Bus': 'PARKING-EXHAUST-MOTOR',
      'To Bus': 'MAIN-DISTRIBUTION',
      'Voltage (V)': 415,
      'Power Factor': 0.83,
      'Efficiency (%)': 89,
      'Derating Factor': 0.89,
      'Breaker Type': 'MCCB-25A',
      'Load KW': 7.5,
      'Load KVA': 9.0,
      'Cable Type': 'PVC',
      'Installation Method': 'Conduit',
      'Ambient Temp (°C)': 38,
      'Ground Temp (°C)': 28,
      'Length (m)': 40.0,
      'Short Circuit Current (kA)': 0,
      'Trip Time (ms)': 0
    },

    // ============ SECTION 2: UPS PANEL (10 items) ============
    {
      'Serial No': 12,
      'Cable Number': 'UPS-HDR-001',
      'Feeder Description': 'UPS PANEL (UNINTERRUPTIBLE POWER SUPPLY)',
      'From Bus': 'UPS-PANEL',
      'To Bus': 'UPS-PANEL',
      'Voltage (V)': 415,
      'Power Factor': 0.90,
      'Efficiency (%)': 95,
      'Derating Factor': 1.0,
      'Breaker Type': 'MCCB',
      'Load KW': 0,
      'Load KVA': 0,
      'Cable Type': 'XLPE',
      'Installation Method': 'Cable Tray',
      'Ambient Temp (°C)': 35,
      'Ground Temp (°C)': 25,
      'Length (m)': 2.0,
      'Short Circuit Current (kA)': 0,
      'Trip Time (ms)': 0
    },

    {
      'Serial No': 13,
      'Cable Number': 'UPS-001',
      'Feeder Description': 'Battery Charger Unit 1 - 18kW',
      'From Bus': 'UPS-CHARGER-1',
      'To Bus': 'UPS-PANEL',
      'Voltage (V)': 415,
      'Power Factor': 0.88,
      'Efficiency (%)': 93,
      'Derating Factor': 0.88,
      'Breaker Type': 'MCCB-63A',
      'Load KW': 18.0,
      'Load KVA': 20.5,
      'Cable Type': 'XLPE',
      'Installation Method': 'Conduit',
      'Ambient Temp (°C)': 38,
      'Ground Temp (°C)': 28,
      'Length (m)': 12.0,
      'Short Circuit Current (kA)': 0,
      'Trip Time (ms)': 0
    },

    {
      'Serial No': 14,
      'Cable Number': 'UPS-002',
      'Feeder Description': 'UPS Inverter Module 1 - 40kW',
      'From Bus': 'UPS-INVERTER-1',
      'To Bus': 'UPS-PANEL',
      'Voltage (V)': 415,
      'Power Factor': 0.92,
      'Efficiency (%)': 96,
      'Derating Factor': 0.91,
      'Breaker Type': 'MCCB-100A',
      'Load KW': 40.0,
      'Load KVA': 43.5,
      'Cable Type': 'XLPE',
      'Installation Method': 'Conduit',
      'Ambient Temp (°C)': 35,
      'Ground Temp (°C)': 25,
      'Length (m)': 8.0,
      'Short Circuit Current (kA)': 0,
      'Trip Time (ms)': 0
    },

    {
      'Serial No': 15,
      'Cable Number': 'UPS-003',
      'Feeder Description': 'Static Bypass Switch - 50kW',
      'From Bus': 'UPS-STATIC-BYPASS',
      'To Bus': 'UPS-PANEL',
      'Voltage (V)': 415,
      'Power Factor': 0.95,
      'Efficiency (%)': 98,
      'Derating Factor': 0.95,
      'Breaker Type': 'MCCB-125A',
      'Load KW': 50.0,
      'Load KVA': 52.6,
      'Cable Type': 'XLPE',
      'Installation Method': 'Conduit',
      'Ambient Temp (°C)': 35,
      'Ground Temp (°C)': 25,
      'Length (m)': 5.0,
      'Short Circuit Current (kA)': 0,
      'Trip Time (ms)': 0
    },

    {
      'Serial No': 16,
      'Cable Number': 'UPS-004',
      'Feeder Description': 'Maintenance Bypass Feeder - 50kW',
      'From Bus': 'UPS-MAINT-BYPASS',
      'To Bus': 'UPS-PANEL',
      'Voltage (V)': 415,
      'Power Factor': 0.94,
      'Efficiency (%)': 97,
      'Derating Factor': 0.94,
      'Breaker Type': 'MCCB-125A',
      'Load KW': 50.0,
      'Load KVA': 53.2,
      'Cable Type': 'XLPE',
      'Installation Method': 'Conduit',
      'Ambient Temp (°C)': 35,
      'Ground Temp (°C)': 25,
      'Length (m)': 10.0,
      'Short Circuit Current (kA)': 0,
      'Trip Time (ms)': 0
    },

    {
      'Serial No': 17,
      'Cable Number': 'UPS-005',
      'Feeder Description': 'Communication Interface Module - 2kW',
      'From Bus': 'UPS-COMM-MODULE',
      'To Bus': 'UPS-PANEL',
      'Voltage (V)': 415,
      'Power Factor': 0.96,
      'Efficiency (%)': 97,
      'Derating Factor': 0.93,
      'Breaker Type': 'MCB-10A',
      'Load KW': 2.0,
      'Load KVA': 2.1,
      'Cable Type': 'PVC',
      'Installation Method': 'Conduit',
      'Ambient Temp (°C)': 35,
      'Ground Temp (°C)': 25,
      'Length (m)': 6.0,
      'Short Circuit Current (kA)': 0,
      'Trip Time (ms)': 0
    },

    {
      'Serial No': 18,
      'Cable Number': 'UPS-006',
      'Feeder Description': 'Battery Bank Protection Board - 1kW',
      'From Bus': 'UPS-BATTERY-PROTECT',
      'To Bus': 'UPS-PANEL',
      'Voltage (V)': 415,
      'Power Factor': 0.95,
      'Efficiency (%)': 98,
      'Derating Factor': 0.92,
      'Breaker Type': 'MCB-6A',
      'Load KW': 1.0,
      'Load KVA': 1.1,
      'Cable Type': 'PVC',
      'Installation Method': 'Conduit',
      'Ambient Temp (°C)': 35,
      'Ground Temp (°C)': 25,
      'Length (m)': 4.0,
      'Short Circuit Current (kA)': 0,
      'Trip Time (ms)': 0
    },

    {
      'Serial No': 19,
      'Cable Number': 'UPS-007',
      'Feeder Description': 'Monitoring & Alarm System - 3kW',
      'From Bus': 'UPS-ALARM-SYSTEM',
      'To Bus': 'UPS-PANEL',
      'Voltage (V)': 415,
      'Power Factor': 0.95,
      'Efficiency (%)': 97,
      'Derating Factor': 0.92,
      'Breaker Type': 'MCB-16A',
      'Load KW': 3.0,
      'Load KVA': 3.2,
      'Cable Type': 'PVC',
      'Installation Method': 'Conduit',
      'Ambient Temp (°C)': 35,
      'Ground Temp (°C)': 25,
      'Length (m)': 8.0,
      'Short Circuit Current (kA)': 0,
      'Trip Time (ms)': 0
    },

    {
      'Serial No': 20,
      'Cable Number': 'UPS-008',
      'Feeder Description': 'Isolation Transformer Output - 45kW',
      'From Bus': 'UPS-ISOL-TRAFO',
      'To Bus': 'UPS-PANEL',
      'Voltage (V)': 415,
      'Power Factor': 0.93,
      'Efficiency (%)': 96,
      'Derating Factor': 0.92,
      'Breaker Type': 'MCCB-125A',
      'Load KW': 45.0,
      'Load KVA': 48.4,
      'Cable Type': 'XLPE',
      'Installation Method': 'Conduit',
      'Ambient Temp (°C)': 35,
      'Ground Temp (°C)': 25,
      'Length (m)': 7.0,
      'Short Circuit Current (kA)': 0,
      'Trip Time (ms)': 0
    },

    {
      'Serial No': 21,
      'Cable Number': 'UPS-009',
      'Feeder Description': 'Emergency Lighting - 4kW',
      'From Bus': 'UPS-EMER-LIGHTING',
      'To Bus': 'UPS-PANEL',
      'Voltage (V)': 415,
      'Power Factor': 0.95,
      'Efficiency (%)': 97,
      'Derating Factor': 0.92,
      'Breaker Type': 'MCB-20A',
      'Load KW': 4.0,
      'Load KVA': 4.2,
      'Cable Type': 'PVC',
      'Installation Method': 'Cable Tray',
      'Ambient Temp (°C)': 35,
      'Ground Temp (°C)': 25,
      'Length (m)': 15.0,
      'Short Circuit Current (kA)': 0,
      'Trip Time (ms)': 0
    },

    // ============ SECTION 3: HVAC PANEL (11 items) ============
    {
      'Serial No': 22,
      'Cable Number': 'HVAC-HDR-001',
      'Feeder Description': 'HVAC CONTROL PANEL (HEATING VENTILATION & COOLING)',
      'From Bus': 'HVAC-PANEL',
      'To Bus': 'HVAC-PANEL',
      'Voltage (V)': 415,
      'Power Factor': 0.85,
      'Efficiency (%)': 94,
      'Derating Factor': 1.0,
      'Breaker Type': 'MCCB',
      'Load KW': 0,
      'Load KVA': 0,
      'Cable Type': 'XLPE',
      'Installation Method': 'Cable Tray',
      'Ambient Temp (°C)': 38,
      'Ground Temp (°C)': 28,
      'Length (m)': 2.0,
      'Short Circuit Current (kA)': 0,
      'Trip Time (ms)': 0
    },

    {
      'Serial No': 23,
      'Cable Number': 'HVAC-001',
      'Feeder Description': 'Air Handling Unit AHU-1 Motor - 22kW',
      'From Bus': 'HVAC-AHU-1-MOTOR',
      'To Bus': 'HVAC-PANEL',
      'Voltage (V)': 415,
      'Power Factor': 0.82,
      'Efficiency (%)': 89,
      'Derating Factor': 0.90,
      'Breaker Type': 'MCCB-80A',
      'Load KW': 22.0,
      'Load KVA': 26.8,
      'Cable Type': 'XLPE',
      'Installation Method': 'Conduit',
      'Ambient Temp (°C)': 38,
      'Ground Temp (°C)': 28,
      'Length (m)': 35.0,
      'Short Circuit Current (kA)': 0,
      'Trip Time (ms)': 0
    },

    {
      'Serial No': 24,
      'Cable Number': 'HVAC-002',
      'Feeder Description': 'Chiller Compressor Motor - 55kW',
      'From Bus': 'HVAC-CHILLER-MOTOR',
      'To Bus': 'HVAC-PANEL',
      'Voltage (V)': 415,
      'Power Factor': 0.80,
      'Efficiency (%)': 88,
      'Derating Factor': 0.88,
      'Breaker Type': 'ACB-160A',
      'Load KW': 55.0,
      'Load KVA': 68.75,
      'Cable Type': 'XLPE',
      'Installation Method': 'Conduit',
      'Ambient Temp (°C)': 40,
      'Ground Temp (°C)': 30,
      'Length (m)': 48.0,
      'Short Circuit Current (kA)': 22,
      'Trip Time (ms)': 150
    },

    {
      'Serial No': 25,
      'Cable Number': 'HVAC-003',
      'Feeder Description': 'Cooling Tower Fan Motor - 18.5kW',
      'From Bus': 'HVAC-COOLING-TOWER',
      'To Bus': 'HVAC-PANEL',
      'Voltage (V)': 415,
      'Power Factor': 0.82,
      'Efficiency (%)': 89,
      'Derating Factor': 0.90,
      'Breaker Type': 'MCCB-63A',
      'Load KW': 18.5,
      'Load KVA': 22.6,
      'Cable Type': 'XLPE',
      'Installation Method': 'Conduit',
      'Ambient Temp (°C)': 40,
      'Ground Temp (°C)': 30,
      'Length (m)': 42.0,
      'Short Circuit Current (kA)': 0,
      'Trip Time (ms)': 0
    },

    {
      'Serial No': 26,
      'Cable Number': 'HVAC-004',
      'Feeder Description': 'Boiler Circulating Pump - 7.5kW',
      'From Bus': 'HVAC-BOILER-PUMP',
      'To Bus': 'HVAC-PANEL',
      'Voltage (V)': 415,
      'Power Factor': 0.84,
      'Efficiency (%)': 91,
      'Derating Factor': 0.89,
      'Breaker Type': 'MCCB-25A',
      'Load KW': 7.5,
      'Load KVA': 8.9,
      'Cable Type': 'PVC',
      'Installation Method': 'Conduit',
      'Ambient Temp (°C)': 40,
      'Ground Temp (°C)': 30,
      'Length (m)': 30.0,
      'Short Circuit Current (kA)': 0,
      'Trip Time (ms)': 0
    },

    {
      'Serial No': 27,
      'Cable Number': 'HVAC-005',
      'Feeder Description': 'Condenser Pump Motor - 5.5kW',
      'From Bus': 'HVAC-CONDENSER-PUMP',
      'To Bus': 'HVAC-PANEL',
      'Voltage (V)': 415,
      'Power Factor': 0.84,
      'Efficiency (%)': 91,
      'Derating Factor': 0.89,
      'Breaker Type': 'MCCB-20A',
      'Load KW': 5.5,
      'Load KVA': 6.5,
      'Cable Type': 'PVC',
      'Installation Method': 'Conduit',
      'Ambient Temp (°C)': 40,
      'Ground Temp (°C)': 30,
      'Length (m)': 38.0,
      'Short Circuit Current (kA)': 0,
      'Trip Time (ms)': 0
    },

    {
      'Serial No': 28,
      'Cable Number': 'HVAC-006',
      'Feeder Description': 'HVAC Control Unit - 4kW',
      'From Bus': 'HVAC-CONTROL-UNIT',
      'To Bus': 'HVAC-PANEL',
      'Voltage (V)': 415,
      'Power Factor': 0.92,
      'Efficiency (%)': 96,
      'Derating Factor': 0.91,
      'Breaker Type': 'MCB-16A',
      'Load KW': 4.0,
      'Load KVA': 4.3,
      'Cable Type': 'PVC',
      'Installation Method': 'Conduit',
      'Ambient Temp (°C)': 35,
      'Ground Temp (°C)': 25,
      'Length (m)': 20.0,
      'Short Circuit Current (kA)': 0,
      'Trip Time (ms)': 0
    },

    {
      'Serial No': 29,
      'Cable Number': 'HVAC-007',
      'Feeder Description': 'Zone Heating/Cooling Valve Actuators - 3kW',
      'From Bus': 'HVAC-ZONE-VALVES',
      'To Bus': 'HVAC-PANEL',
      'Voltage (V)': 415,
      'Power Factor': 0.90,
      'Efficiency (%)': 95,
      'Derating Factor': 0.90,
      'Breaker Type': 'MCB-13A',
      'Load KW': 3.0,
      'Load KVA': 3.3,
      'Cable Type': 'PVC',
      'Installation Method': 'Conduit',
      'Ambient Temp (°C)': 35,
      'Ground Temp (°C)': 25,
      'Length (m)': 25.0,
      'Short Circuit Current (kA)': 0,
      'Trip Time (ms)': 0
    },

    {
      'Serial No': 30,
      'Cable Number': 'HVAC-008',
      'Feeder Description': 'Fresh Air Damper Actuators - 2.2kW',
      'From Bus': 'HVAC-DAMPER-ACTUATORS',
      'To Bus': 'HVAC-PANEL',
      'Voltage (V)': 415,
      'Power Factor': 0.90,
      'Efficiency (%)': 95,
      'Derating Factor': 0.90,
      'Breaker Type': 'MCB-10A',
      'Load KW': 2.2,
      'Load KVA': 2.4,
      'Cable Type': 'PVC',
      'Installation Method': 'Conduit',
      'Ambient Temp (°C)': 35,
      'Ground Temp (°C)': 25,
      'Length (m)': 22.0,
      'Short Circuit Current (kA)': 0,
      'Trip Time (ms)': 0
    },

    {
      'Serial No': 31,
      'Cable Number': 'HVAC-009',
      'Feeder Description': 'Chiller Condenser Fan - 11kW',
      'From Bus': 'HVAC-CONDENSER-FAN',
      'To Bus': 'HVAC-PANEL',
      'Voltage (V)': 415,
      'Power Factor': 0.82,
      'Efficiency (%)': 89,
      'Derating Factor': 0.90,
      'Breaker Type': 'MCCB-40A',
      'Load KW': 11.0,
      'Load KVA': 13.4,
      'Cable Type': 'XLPE',
      'Installation Method': 'Conduit',
      'Ambient Temp (°C)': 40,
      'Ground Temp (°C)': 30,
      'Length (m)': 45.0,
      'Short Circuit Current (kA)': 0,
      'Trip Time (ms)': 0
    },

    {
      'Serial No': 32,
      'Cable Number': 'HVAC-010',
      'Feeder Description': 'Vibration Monitoring System - 1.5kW',
      'From Bus': 'HVAC-VIBRATION-MON',
      'To Bus': 'HVAC-PANEL',
      'Voltage (V)': 415,
      'Power Factor': 0.95,
      'Efficiency (%)': 97,
      'Derating Factor': 0.92,
      'Breaker Type': 'MCB-8A',
      'Load KW': 1.5,
      'Load KVA': 1.6,
      'Cable Type': 'PVC',
      'Installation Method': 'Conduit',
      'Ambient Temp (°C)': 35,
      'Ground Temp (°C)': 25,
      'Length (m)': 28.0,
      'Short Circuit Current (kA)': 0,
      'Trip Time (ms)': 0
    },

    // ============ SECTION 4: LIGHTING PANEL (11 items) ============
    {
      'Serial No': 33,
      'Cable Number': 'LTG-HDR-001',
      'Feeder Description': 'LIGHTING DISTRIBUTION PANEL',
      'From Bus': 'LIGHTING-PANEL',
      'To Bus': 'LIGHTING-PANEL',
      'Voltage (V)': 415,
      'Power Factor': 0.95,
      'Efficiency (%)': 98,
      'Derating Factor': 1.0,
      'Breaker Type': 'MCCB',
      'Load KW': 0,
      'Load KVA': 0,
      'Cable Type': 'XLPE',
      'Installation Method': 'Cable Tray',
      'Ambient Temp (°C)': 35,
      'Ground Temp (°C)': 25,
      'Length (m)': 2.0,
      'Short Circuit Current (kA)': 0,
      'Trip Time (ms)': 0
    },

    {
      'Serial No': 34,
      'Cable Number': 'LTG-001',
      'Feeder Description': 'Floor 1 Lighting Circuit - 12kW',
      'From Bus': 'LIGHTING-FLOOR-1',
      'To Bus': 'LIGHTING-PANEL',
      'Voltage (V)': 415,
      'Power Factor': 0.95,
      'Efficiency (%)': 98,
      'Derating Factor': 0.92,
      'Breaker Type': 'MCCB-40A',
      'Load KW': 12.0,
      'Load KVA': 12.6,
      'Cable Type': 'PVC',
      'Installation Method': 'Cable Tray',
      'Ambient Temp (°C)': 35,
      'Ground Temp (°C)': 25,
      'Length (m)': 28.0,
      'Short Circuit Current (kA)': 0,
      'Trip Time (ms)': 0
    },

    {
      'Serial No': 35,
      'Cable Number': 'LTG-002',
      'Feeder Description': 'Floor 2 Lighting Circuit - 12kW',
      'From Bus': 'LIGHTING-FLOOR-2',
      'To Bus': 'LIGHTING-PANEL',
      'Voltage (V)': 415,
      'Power Factor': 0.95,
      'Efficiency (%)': 98,
      'Derating Factor': 0.92,
      'Breaker Type': 'MCCB-40A',
      'Load KW': 12.0,
      'Load KVA': 12.6,
      'Cable Type': 'PVC',
      'Installation Method': 'Cable Tray',
      'Ambient Temp (°C)': 35,
      'Ground Temp (°C)': 25,
      'Length (m)': 32.0,
      'Short Circuit Current (kA)': 0,
      'Trip Time (ms)': 0
    },

    {
      'Serial No': 36,
      'Cable Number': 'LTG-003',
      'Feeder Description': 'Floor 3 Lighting Circuit - 12kW',
      'From Bus': 'LIGHTING-FLOOR-3',
      'To Bus': 'LIGHTING-PANEL',
      'Voltage (V)': 415,
      'Power Factor': 0.95,
      'Efficiency (%)': 98,
      'Derating Factor': 0.92,
      'Breaker Type': 'MCCB-40A',
      'Load KW': 12.0,
      'Load KVA': 12.6,
      'Cable Type': 'PVC',
      'Installation Method': 'Cable Tray',
      'Ambient Temp (°C)': 35,
      'Ground Temp (°C)': 25,
      'Length (m)': 36.0,
      'Short Circuit Current (kA)': 0,
      'Trip Time (ms)': 0
    },

    {
      'Serial No': 37,
      'Cable Number': 'LTG-004',
      'Feeder Description': 'Outdoor Parking Lights - 8kW',
      'From Bus': 'LIGHTING-OUTDOOR-PARKING',
      'To Bus': 'LIGHTING-PANEL',
      'Voltage (V)': 415,
      'Power Factor': 0.95,
      'Efficiency (%)': 98,
      'Derating Factor': 0.92,
      'Breaker Type': 'MCCB-32A',
      'Load KW': 8.0,
      'Load KVA': 8.4,
      'Cable Type': 'PVC',
      'Installation Method': 'Cable Tray',
      'Ambient Temp (°C)': 35,
      'Ground Temp (°C)': 25,
      'Length (m)': 50.0,
      'Short Circuit Current (kA)': 0,
      'Trip Time (ms)': 0
    },

    {
      'Serial No': 38,
      'Cable Number': 'LTG-005',
      'Feeder Description': 'Outdoor Building Facade Lights - 5kW',
      'From Bus': 'LIGHTING-FACADE',
      'To Bus': 'LIGHTING-PANEL',
      'Voltage (V)': 415,
      'Power Factor': 0.95,
      'Efficiency (%)': 98,
      'Derating Factor': 0.92,
      'Breaker Type': 'MCB-20A',
      'Load KW': 5.0,
      'Load KVA': 5.3,
      'Cable Type': 'PVC',
      'Installation Method': 'Cable Tray',
      'Ambient Temp (°C)': 35,
      'Ground Temp (°C)': 25,
      'Length (m)': 45.0,
      'Short Circuit Current (kA)': 0,
      'Trip Time (ms)': 0
    },

    {
      'Serial No': 39,
      'Cable Number': 'LTG-006',
      'Feeder Description': 'Common Area & Corridor Lights - 6kW',
      'From Bus': 'LIGHTING-COMMON-AREA',
      'To Bus': 'LIGHTING-PANEL',
      'Voltage (V)': 415,
      'Power Factor': 0.95,
      'Efficiency (%)': 98,
      'Derating Factor': 0.92,
      'Breaker Type': 'MCB-24A',
      'Load KW': 6.0,
      'Load KVA': 6.3,
      'Cable Type': 'PVC',
      'Installation Method': 'Cable Tray',
      'Ambient Temp (°C)': 35,
      'Ground Temp (°C)': 25,
      'Length (m)': 22.0,
      'Short Circuit Current (kA)': 0,
      'Trip Time (ms)': 0
    },

    {
      'Serial No': 40,
      'Cable Number': 'LTG-007',
      'Feeder Description': 'Stairwell Emergency Lighting - 3kW',
      'From Bus': 'LIGHTING-STAIRWELL',
      'To Bus': 'LIGHTING-PANEL',
      'Voltage (V)': 415,
      'Power Factor': 0.95,
      'Efficiency (%)': 98,
      'Derating Factor': 0.92,
      'Breaker Type': 'MCB-13A',
      'Load KW': 3.0,
      'Load KVA': 3.2,
      'Cable Type': 'PVC',
      'Installation Method': 'Cable Tray',
      'Ambient Temp (°C)': 35,
      'Ground Temp (°C)': 25,
      'Length (m)': 35.0,
      'Short Circuit Current (kA)': 0,
      'Trip Time (ms)': 0
    },

    {
      'Serial No': 41,
      'Cable Number': 'LTG-008',
      'Feeder Description': 'Loading Dock Area Lights - 4kW',
      'From Bus': 'LIGHTING-LOADING-DOCK',
      'To Bus': 'LIGHTING-PANEL',
      'Voltage (V)': 415,
      'Power Factor': 0.95,
      'Efficiency (%)': 98,
      'Derating Factor': 0.92,
      'Breaker Type': 'MCB-16A',
      'Load KW': 4.0,
      'Load KVA': 4.2,
      'Cable Type': 'PVC',
      'Installation Method': 'Cable Tray',
      'Ambient Temp (°C)': 35,
      'Ground Temp (°C)': 25,
      'Length (m)': 38.0,
      'Short Circuit Current (kA)': 0,
      'Trip Time (ms)': 0
    },

    {
      'Serial No': 42,
      'Cable Number': 'LTG-009',
      'Feeder Description': 'Warehouse High Bay Lights - 7kW',
      'From Bus': 'LIGHTING-HIGH-BAY',
      'To Bus': 'LIGHTING-PANEL',
      'Voltage (V)': 415,
      'Power Factor': 0.95,
      'Efficiency (%)': 98,
      'Derating Factor': 0.92,
      'Breaker Type': 'MCCB-25A',
      'Load KW': 7.0,
      'Load KVA': 7.4,
      'Cable Type': 'PVC',
      'Installation Method': 'Cable Tray',
      'Ambient Temp (°C)': 35,
      'Ground Temp (°C)': 25,
      'Length (m)': 42.0,
      'Short Circuit Current (kA)': 0,
      'Trip Time (ms)': 0
    },

    {
      'Serial No': 43,
      'Cable Number': 'LTG-010',
      'Feeder Description': 'Sensor & Control Lighting - 2.5kW',
      'From Bus': 'LIGHTING-SENSORS',
      'To Bus': 'LIGHTING-PANEL',
      'Voltage (V)': 415,
      'Power Factor': 0.95,
      'Efficiency (%)': 98,
      'Derating Factor': 0.92,
      'Breaker Type': 'MCB-10A',
      'Load KW': 2.5,
      'Load KVA': 2.6,
      'Cable Type': 'PVC',
      'Installation Method': 'Conduit',
      'Ambient Temp (°C)': 35,
      'Ground Temp (°C)': 25,
      'Length (m)': 18.0,
      'Short Circuit Current (kA)': 0,
      'Trip Time (ms)': 0
    }
  ];
};
